### PR TITLE
Create option to divide by output count

### PR DESCRIPTION
**Pull request by CodingBenny**
I made a checkbox option in the recipe controler, so that the player can choose.

### CODE REVIEW

**Comment by theRustyKnife** [comment]
This looks a lot more like something I'd accept. I'll review it once I get to the computer.

**Comment by theRustyKnife** [comment]
So I've been messing around with this a bit and I still don't like the way the product is selected. The signals are just too decoupled from the recipe itself. This is a problem for a lot of modded recipes, which have different names from their products.

Recipes with just one product could be fixed by simply assuming that that product is the one to divide by.

As for recipes with multiple products, it's going to be somewhat more complex. The product matching the signal should probably be preferred. If there isn't such product, but `main_product` is specified, use that. If that's not the case either, just take the first product or something like that (this is kinda dumb, but better than nothing).

I'll probably give this a shot tomorrow.

**Comment by CodingBenny** [comment]
> This is a problem for a lot of modded recipes, which have different names from their products.

So to automate that you would need a "find recipes" combinator and a "find ingredients" combinator? Because a single  "find ingredients" would not work? You are right in that case diving like this would not make any sense.

> If there isn't such product, but main_product is specified, use that. 

I did not know that existed.

Just picking the first signal as a last resort will probably lead to completly unpredictable behaivior.

**Comment by CodingBenny** [comment]
Ok, in the case where the recipe name does not match the product name, you need 2 recipe combinators anyway. I made the division work for "find recipe" as well now. This way the second combinator only has to multiply the times you need the recipes by the number of ingredients.

Here is an example of which recipes you need to make 345 heavy oil:
recipes

**Comment by theRustyKnife** [comment]
Sorry, ended up not having time yesterday.

> I made the division work for "find recipe" as well now. This way the second combinator only has to multiply the times you need the recipes by the number of ingredients.

I'm wondering whether it wouldn't be best to only allow this. It seems like the most consistent solution so far, albeit at the expense of an extra combinator being required for the "simple" recipes.

An issue I see with this is that selecting the desired recipe from the output to multiply by would be a bit of a pain. Tho that's been the case with the recipe mode already, so I'm not too bothered by that. Besides, if you don't care, the recipe combinator finding the ingredients will just select one for you, so that's fine.

I would also make the checkbox for this hidden unless the combinator is in recipe mode, so it's clear that it only works for that. It would require some changes to how the gui works tho, so I'd probably just do that later.

What do you think about that?

**Comment by CodingBenny** [comment]
> An issue I see with this is that selecting the desired recipe from the output to multiply by would be a bit of a pain. Tho that's been the case with the recipe mode already, so I'm not too bothered by that. 

That is a lot easier to do that with decider combinators when the recipes have different signals strengths.

> I would also make the checkbox for this hidden unless the combinator is in recipe mode, so it's clear that it only works for that.

It works for all modes. It just does nothing when "multiply by input" is disabled because of the small numbers. So i would rather hide or block it when that is not checked instead of depending on the mode.

**Comment by theRustyKnife** [comment]
>> I would also make the checkbox for this hidden unless the combinator is in recipe mode, so it's clear that it only works for that.

> It works for all modes. It just does nothing when "multiply by input" is disabled because of the small numbers. So i would rather hide or block it when that is not checked instead of depending on the mode.

I think we don't understand each other completely here... I know it works for modes other than recipe as it is now. What I meant by that was that it might be best to only *let* the player use this in recipe mode, since that's the only one that actually behaves predictably for any recipe. So the reason for hiding the checkbox in other modes was that we don't *want* it to work, rather than that it *doesn't* work.

This is also what I was asking about: How do you feel about ditching this for all modes except recipe and just leaving it up to the player to use another combinator to calculate the ingredients? To me this seems like the best option so far.

That being said, your point is still valid too, since it will probably just always end up being one without the multiply by input option enabled. I'm not sure about this tho, because I feel like hiding it for this too would make it *too* difficult to find.

>> An issue I see with this is that selecting the desired recipe from the output to multiply by would be a bit of a pain. Tho that's been the case with the recipe mode already, so I'm not too bothered by that.

> That is a lot easier to do that with decider combinators when the recipes have different signals strengths.

Yes, however the real problem is selecting the recipe that the player actually wants to use, which is difficult. But as I said, this has been a problem with the recipe mode for a long time and nobody seems to be too bothered by it, so I don't really care.

**Comment by CodingBenny** [comment]
> What I meant by that was that it might be best to only let the player use this in recipe mode, since that's the only one that actually behaves predictably for any recipe.

Do you have an example recipe where it is unpredictable in ingredients mode?

**Comment by theRustyKnife** [comment]
Well, there's the example of recipes with names different than results. In vanilla, this would apply to the barreling recipes for instance.

But really my biggest gripe with this is for recipes with multiple results, where *if* this were to work at all, it would only work for one of the results. Again, if we look at vanilla, oil processing comes to mind. The recipes for it have multiple results, of which you could only use one in ingredient mode, yet depending on which one you choose, you'd get different output.

**Comment by CodingBenny** [comment]
I am not sure what you mean.

> Well, there's the example of recipes with names different than results. In vanilla, this would apply to the barreling recipes for instance.

In that case ingredient mode outputs nothing. The checkbox options are not important then.

> Again, if we look at vanilla, oil processing comes to mind. The recipes for it have multiple results, of which you could only use one in ingredient mode, yet depending on which one you choose, you'd get different output.

In ingredient mode you would not get an output if you use one of the products as input signal.

Or do you mean this: You have a recipe with multiple products and the recipe name is equal to one of them. In this case you would only get an output for the product that has the recipe name and it would be correctly divided.

You only can get an output in incredients mode if you have the name of the recipe.
And then there are two options:
1. The recipe name is the name of a product and you can divide by it. (In vanilla there are only recipes with one product where the recipe name is the same as a product)
1. The recipe name is not a name of a product and nothing is divided.

**Comment by theRustyKnife** [comment]
> 1. The recipe name is the name of a product and you can divide by it. (In vanilla there are only recipes with one product where the recipe name is the same as a product)
> 2. The recipe name is not a name of a product and nothing is divided.

This is one of the problems I have: It behaves differently for different recipes (divides some, doesn't divide others). Also, the fact that there are no such recipes in vanilla doesn't mean the mod doesn't have to support them, just to be clear.

The other problem is kind of a step beyond, where I assume we find a way to do the division for any recipe, regardless of the name issue and how many products it has. Then for example if you have an rc in ingredient mode with 100 advanced oil processing on the input, it would give different outputs, depending on which product you decide to divide by: if you divide by heavy oil, you'll get 500 water and 1000 crude, but if you divide by light oil, you'll get 150 water and 300 crude.

This on it's own would be fine if there was a way for the player to choose which to divide by, but that isn't really possible as far as I can tell. Thus it would have to be decided by the mod, effectively only making it possible to divide by one of the products.

I'm sorry if I sound annoying with all this, but I already get too many questions about how the recipes are signaled, which unfortunately just can't be done in any better way. That's why I really don't want to add anything that's inconsistent or depends on stuff that's not visible to the player like that does.

In this case, there are none of those problems with implementing it only for recipe mode, so I'd say it's a good way to do it, even though it means the player has to use an extra combinator in some simple cases.

**Comment by CodingBenny** [comment]
> Then for example if you have an rc in ingredient mode with 100 advanced oil processing on the input, it would give different outputs, depending on which product you decide to divide by: if you divide by heavy oil, you'll get 500 water and 1000 crude, but if you divide by light oil, you'll get 150 water and 300 crude.

That is why it currently does not divide when it has oil processing as input. 


> This on it's own would be fine if there was a way for the player to choose which to divide by, but that isn't really possible as far as I can tell. Thus it would have to be decided by the mod, effectively only making it possible to divide by one of the products.

I argee. It can't be decided by the mod. Since we dont know what product the player is going for when we only have the recipe as an input.

> I'm sorry if I sound annoying with all this

Better a bit of arguing than having something in there that you dont like.

>  I already get too many questions about how the recipes are signaled

I think thats because it is a bit confusing to have no difference between recipe and product most of the time. Before you told me I had no idea that you should use one in recipe mode and one ingredients mode chained up.
What do you think about naming the modes "find recipe by product", "find ingredients by recipe" and "find products by recipe"? That could hint the excepted input.

> In this case, there are none of those problems with implementing it only for recipe mode, so I'd say it's a good way to do it, even though it means the player has to use an extra combinator in some simple cases.

Ok, i can understand that. It is better to not have a shortcut that does not work as soon as a mod adds an assembler recipe with multiple products.
I am going to commit a recipe mode only division.

**Comment by CodingBenny** [comment]
I did not hide it, I disabled it because otherwise the gui is shaking.

**Comment by theRustyKnife** [comment]
Nice, glad we finally settled on this. I'll have a proper look at it on Tuesday probably, since I have some exams coming up. I like it tho, at least based on what I just tested in a couple minutes.

**Comment by theRustyKnife** [comment]
Sorry for the delay, got caught up in IRL stuff. I will merge this now, although there are some minor issues, like that there's no default for the new setting and that the checkbox doesn't get disabled when the gui is first created. I'll just fix that myself tho, since I have the time for it now.

I also have a question: Was there some problem with multiplying by the probability? To me it seems a lot more accurate to do it rather than not, since for example uranium 235 only has 0.7% chance in uranium processing, so without taking that into account, the result is significantly overestimated.  
Anyway, if I decide I want to keep it, I'll just commit it back in, so no need to update this PR anymore.

**Comment by CodingBenny** [comment]
Oh yeah, i missed the default settings part. Sorry about that.

The uranium was exactly the reason i tried to add the probability. The only reason why i commented it out is that it is only an estimate. If you are crafting things automaticly there is a very high chance that you will end up without enough items for the next crafting step.
So i thought that this was not a very clean solution.

On the other hand if you don't include the probability your result is way more off.

The reason i left it as a comment was to let you decide what to do with it.

**Comment by theRustyKnife** [comment]
Hmm, you have a point there. But I still feel like it's better to include it, since the results are far closer to the actual value. In other words, I think it's worse to have the player craft hundreds of times more items than they need, than a couple fewer. I guess it's gonna be one of the things the player just has to deal with themselves somehow.

I really should start some FAQ or something for these things tho, since there's already so many things that are useful to know, but not immediately obvious and this is a thing that really should be mentioned somewhere...

**Comment by CodingBenny** [comment]
> But I still feel like it's better to include it, since the results are far closer to the actual value.

Yeah, there is a ~50% chance it works out for them.

The readme and factorio mod page could be used for the FAQ.
I did not add anything about the new modes to the readme.

**Comment by theRustyKnife** [comment]
Oh right, the read readme does need an update :| Thanks for reminding me.

There's also a dedicated FAQ tab on the mod portal, so I might try that out.

**Pull request merged**
