### PR TITLE
Fix for Issue #53

### PR DESCRIPTION
**Pull request by CodingBenny**
I added a check for recipes that have no virtual signal. They are omitted.

There is no way to add recipe signals for mods that are run later than crafting combinators data-final-fixes.lua

I dont think there is a good way to make sure that this mods final fixes are run last.

### CODE REVIEW

**Comment by CodingBenny** [comment]
See #53

**Comment by theRustyKnife** [comment]
I actually left this unchecked intentionally. That way people would report mods that break with a clear error message, instead of it just failing silently. I probably should have added a check for it and thrown the error explicitly so it would be clear that it was intentional, but eh...

That being said, I did have an idea: With a bit of abuse of metatables and the debug library, I may be able to detect when recipe prototypes are added after data-final-fixes and make signals for them if necessary. I just never got around to actually mess with it yet...

**Comment by CodingBenny** [comment]
I can see why you dont want to handle that silently, but I was playing with friends and we lost 8 minutes of gameplay because of it.
So if it crashes it should crash either on starting the game or just print a message to chat.

Meta tables seem a bit hacky to me, but adding everything as dependency is definitely worse.

**Comment by theRustyKnife** [comment]
I did some experiments and came up with 08d426ccf4d857d40bc3ac56291772572ab39e4a. It was actually a lot easier than I thought and not even too hacky... Would you mind giving it a go to see if it actually works? Just keep in mind that you need to remove the dependencies.

**Comment by CodingBenny** [comment]
It works perfectly.

**Pull request closed without merging**
