### PR TITLE
Added usage mode

### PR DESCRIPTION
**Pull request by CodingBenny**
I updated the README as well.
The output division text and the name and tooltip of the new mode would need to be updated in Czech again.

### CODE REVIEW

**Comment by theRustyKnife** [comment]
You must be building something pretty cool with all these PRs, huh?

I like the idea, tho I'd maybe suggest renaming it to something like "Usage mode" or "Find Uses". I feel like that would be a bit more intuitive. I haven't really reviewed the code yet, but that might just have to wait, because I'm a bit too tired to think straight rn...

**Comment by CodingBenny** [comment]
Oh yeah, i like your names way better than mine.
My names are a bit too long.

**Comment by CodingBenny** [comment]
> You must be building something pretty cool with all these PRs, huh?

I just needed a way to get my ores smelted without knowing what item they produce:
grafik
In Usage mode i can easily find all recipes that use hot air and the right ores. They have a signal strengh of 2 here.

**Comment by CodingBenny** [comment]
👍

**Pull request merged**
